-- AssetCore Enterprise EAM Schema
-- Run this in Supabase SQL Editor

-- Categories
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz default now() not null
);

-- Locations
create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text unique,
  created_at timestamptz default now() not null
);

-- Users / PIC
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text unique,
  role text default 'user',
  created_at timestamptz default now() not null
);

-- Assets
create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  asset_tag text not null unique,
  serial_number text unique,
  name text not null,
  specification text,
  category_id bigint references public.categories(id),
  location_id bigint references public.locations(id),
  user_id bigint references public.users(id),
  acquisition_value numeric,
  acquisition_date date,
  status text not null default 'aktif',
  image_url text,
  notes text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists idx_assets_status on public.assets(status);
create index if not exists idx_assets_category on public.assets(category_id);
create index if not exists idx_assets_location on public.assets(location_id);

-- Enable RLS
alter table public.categories enable row level security;
alter table public.locations enable row level security;
alter table public.users enable row level security;
alter table public.assets enable row level security;

-- RLS Policies for anon key (public read/write)
create policy "public_read_categories" on public.categories for select to anon using (true);
create policy "public_read_locations" on public.locations for select to anon using (true);
create policy "public_read_users" on public.users for select to anon using (true);
create policy "public_read_assets" on public.assets for select to anon using (true);
create policy "public_insert_assets" on public.assets for insert to anon with check (true);
create policy "public_update_assets" on public.assets for update to anon using (true);
create policy "public_delete_assets" on public.assets for delete to anon using (true);

-- Seed categories
insert into public.categories (name, slug) values
  ('IT Hardware & Server', 'it-hardware'),
  ('Mesin & Robotik Industri', 'mesin-industri'),
  ('Armada Kendaraan Logistik', 'kendaraan'),
  ('Peralatan Medis & Lab', 'medis-lab'),
  ('Inventaris Fasilitas Kantor', 'kantor')
on conflict (slug) do nothing;

-- Seed locations
insert into public.locations (name, code) values
  ('Kantor Pusat Jakarta - Gedung A', 'KP-JKT'),
  ('Data Center Tier-3 Cibitung', 'DC-CBT'),
  ('Pabrik Perakitan Karawang', 'PB-KRW'),
  ('Hub Logistik Rungkut Surabaya', 'HUB-SBY'),
  ('Warehouse Sentral Cikarang', 'WH-CIKARANG')
on conflict (code) do nothing;

-- Seed sample users
insert into public.users (full_name, email, role) values
  ('Hendra Kusuma', 'hendra@example.com', 'DevOps'),
  ('Bagas Prakoso', 'bagas@example.com', 'Principal Architect'),
  ('Dedi Rusli', 'dedi@example.com', 'Supervisor Logistik'),
  ('Agus Suherman', 'agus@example.com', 'Driver Armada'),
  ('Nurul Novita', 'nurul@example.com', 'QA Head'),
  ('Teguh Maulana', 'teguh@example.com', 'Facility Lead'),
  ('Farah Anindya', 'farah@example.com', 'Lead BIM Modeler')
on conflict (email) do nothing;

-- Seed sample assets
insert into public.assets (asset_tag, serial_number, name, specification, category_id, location_id, user_id, acquisition_value, acquisition_date, status, image_url, notes)
select 'AST-IT-2024-0089', 'DL-R750-99882', 'Server Dell PowerEdge R750', 'Dual Xeon 6330, 256GB ECC, 8TB NVMe Enterprise', c.id, l.id, u.id, 185000000, '2023-04-14', 'Aktif', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDOc7LvI91IrWA1UKIpVzSvXt3uAg2hTI4Jtv5jgDt4P109MlntUTbCVQPrVALL4fg4IXmJ_dNjo_pyqAEWH6zv7vAT7wXGFAoj9mDMUNmVtl5NTLsTibtlMeUzhq3EFv8dmvV9Lfp-C1W1wAJhs6d7O_W1AXmOYHjx8PX-bJ0xTTdzvyH9DkUh0hRiv0argY9e8yC8my3CCi925JEyQAkaoM_KqZgv2pEJjAV4YmIjTsVlSCu45G9w', 'Tier 1 Critical Asset'
from public.categories c, public.locations l, public.users u
where c.slug = 'it-hardware' and l.code = 'DC-CBT' and u.email = 'hendra@example.com'
on conflict (asset_tag) do nothing;

insert into public.assets (asset_tag, serial_number, name, specification, category_id, location_id, user_id, acquisition_value, acquisition_date, status, image_url)
select 'AST-IT-2024-0312', 'C02X87J0MD6T', 'MacBook Pro 16" M3 Max', 'Apple Silicon 16-Core, 64GB Unified Memory, 1TB SSD', c.id, l.id, u.id, 58900000, '2024-01-10', 'Aktif', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCeTDWnGfBXyagiynbUS84--6Gye65cbGzVtchmeg0-TDLX267F1U3824Ma_rFJqTOoDwgns8K0hQsB3nORR5Tqgn2WxIB1S8uEV0mah-cpCKIpj9-yTWNtn-_v1oCtXR_js4_e2bcoBxaDLhGfo070sY_-hcE-o4zd1dIffsex9tB-PGuaHmBYaNDn6fvH4WjO7-g0EFAVDYEWvbpDLKPLDGBaA5gEYkYOr7AQpkPLD-UNMNLImLlb'
from public.categories c, public.locations l, public.users u
where c.slug = 'it-hardware' and l.code = 'KP-JKT' and u.email = 'bagas@example.com'
on conflict (asset_tag) do nothing;

insert into public.assets (asset_tag, serial_number, name, specification, category_id, location_id, user_id, acquisition_value, acquisition_date, status, image_url)
select 'AST-IND-2023-0041', 'TY-FL25-44109', 'Forklift Elektrik Toyota 2.5T', 'Model 8FBN25, AC Drive System 48V Lithium Battery', c.id, l.id, u.id, 340000000, '2023-08-05', 'Maintenance', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDeqYD6v3JIhxRb1ef5Uxh6rvXtKBzLsdDowv-LCLvGQlLiAXoYc8UMOY15VI3Ta28RpTqpMazah0qS8TVgsYfAwmpfLxt-kX1tpeSwg7dZkmyh7spKSJFR-XtEkwBq2rBtmloLc0NhS2oftA1CyVjAGISXPvWCC0YxVBR3z2q079RBLMA8CA5vevUE-tznJ5XX1_lxmAoqmzgqxBY-6Y2-OzMuftZOD__rSshQoNlx-rOLUmhlm9sM'
from public.categories c, public.locations l, public.users u
where c.slug = 'mesin-industri' and l.code = 'HUB-SBY' and u.email = 'dedi@example.com'
on conflict (asset_tag) do nothing;

insert into public.assets (asset_tag, serial_number, name, specification, category_id, location_id, user_id, acquisition_value, acquisition_date, status, image_url)
select 'AST-VH-2022-0115', 'B 9421 KXT', 'Isuzu Giga Wing Box FVR 34', '6 Cylinder Common Rail 285 PS, Panjang Box 9.6 Meter', c.id, l.id, u.id, 820000000, '2022-03-18', 'Dipinjam', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAFTf5m89AW17lXQNr_acV3hPV4jfkA27POYIWWk3V9t5R7Js1Kq226JnB4K2ET3B-GvRsVWBdHJnACc_qY7OUAhTp7Q3I6P8n0drUPMFaVk9-Tnnc8k7XGv3qKw9lXn7XfYlAJ_3qtgJ6pHSolr2qG0XxUiW3n67XkGSXQNTzZBPcumx5WCU5bWlVj-ob5SKPzK3Y9zIK0vzgSJx5gHcb-rDbatDwsZfavP4elShJ7FJaxOk2TGVRw'
from public.categories c, public.locations l, public.users u
where c.slug = 'kendaraan' and l.code = 'WH-CIKARANG' and u.email = 'agus@example.com'
on conflict (asset_tag) do nothing;

insert into public.assets (asset_tag, serial_number, name, specification, category_id, location_id, user_id, acquisition_value, acquisition_date, status, image_url)
select 'AST-LAB-2023-0504', 'SH-UV2600-771', 'Shimadzu UV-2600i Spectrophotometer', 'Double-beam Optical System, Lo-Ray-Ligh Diffraction Grating', c.id, l.id, u.id, 210500000, '2023-11-12', 'Aktif', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDM0OPqnDD2Gg8o9_sSQ0jAv6PNkhFKGfHPtBXNWZDBhX0MOsM725IeTjgLdSleads7_U_pQGFUJwjV2CIsUrFnw3zXGeB8iCmdZ5z5AfNfvV8bFBgRdL74A_PNy32ZTjf-0FGQMwbc9_JY0vDCCD2EvGnU-HMVi7Pkvz-zboFrYymb2taqtoxTgFrjS9M2GxpTlLt7MxtJoH5H2bUXaXpigmSVIarg8KuHXY-16fqYrXR21qb4VNS8'
from public.categories c, public.locations l, public.users u
where c.slug = 'medis-lab' and l.code = 'PB-KRW' and u.email = 'nurul@example.com'
on conflict (asset_tag) do nothing;

insert into public.assets (asset_tag, serial_number, name, specification, category_id, location_id, user_id, acquisition_value, acquisition_date, status, image_url)
select 'AST-FAC-2021-0003', 'CUM-500KVA-11', 'Genset Cummins Silent 500 kVA', 'Engine QSX15-G8, Stamford Alternator, Auto Transfer Switch', c.id, l.id, u.id, 645000000, '2021-02-03', 'Kritis', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAnkuSMoccIU1xftcWE6s-d-_7pC5LbFMyE_xBcoURcSNmCNtCVabMgSLixH-UzPlw668lDCZJNs8zSd-Tj5FNStgrVwN9mLFHeBhN2Tinr4LCfE-os7hUMfJYe3YYXlvxt2SJANfmkkI8RMr2IN3a08r994O93xKa03qdx7Yrnl8WoLbrCRKbxLc0OBx2ADwivqU5KmicVa9nOCxxT6OBiU6KMNBNjQL_5On7aRwfmMtSNHYnv9SNd'
from public.categories c, public.locations l, public.users u
where c.slug = 'kantor' and l.code = 'DC-CBT' and u.email = 'teguh@example.com'
on conflict (asset_tag) do nothing;

insert into public.assets (asset_tag, serial_number, name, specification, category_id, location_id, user_id, acquisition_value, acquisition_date, status, image_url)
select 'AST-IT-2023-0941', 'DELL-WRK-5820', 'Dell Precision 5820 Tower', 'Intel Xeon W-2245, 128GB RAM, Nvidia RTX A5000 24GB', c.id, l.id, u.id, 74200000, '2023-09-19', 'Aktif', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAdYjmP05t86rezDQR9C7hBWY9pUYVDenzqVUf4s839rXTCl4Gfhl81C2W8bdAKmVtsJk_Dxh0wBEcokeVrXUYv54YvChUGLJdLWQR07hswgBz_vXaOMs187aRE6ym0RnqFGhCULgYAH9j-hgXQOgEgahut0DtUtmbn1Bvd-q25XfMPydwweQerGb9aQffc48q5WOMBnbHmy0b7qFzh9EN3CmyQ9k7VPe2MKjVIO8qvzuxK5GNaS4i2'
from public.categories c, public.locations l, public.users u
where c.slug = 'it-hardware' and l.code = 'KP-JKT' and u.email = 'farah@example.com'
on conflict (asset_tag) do nothing;
